name: Build and Release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up CMake
          uses: jwlawson/actions-setup-cmake@v2
          with:
            cmake-version: '3.29'

        - name: Configure
          run: cmake -B build

        - name: Build
          run: cmake --build build

        - name: Create Archive
          run: |
            mkdir -p release/include
            mkdir -p release/lib
            cp -r includes/* release/include
            cp build/*.a release/lib
            tar -czvf CContainer.tar.gz release
          shell: bash

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: CContainer.tar.gz
            path: CContainer.tar.gz

    release:
        needs: build
        runs-on: ubuntu-latest

        steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: CContainer.tar.gz

        - name: Release
          uses: softprops/action-gh-release@v2
          with:
            files: CContainer.tar.gz
            repository: ${{ github.repository }}
            token: ${{ secrets.ACTION_RELEASE }}

			