name: Build and Release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up CMake
          uses: jwlawson/actions-setup-cmake@v2
          with:
            cmake-version: '3.29'

        - name: Configure
          run: cmake -B build

        - name: Build
          run: cmake --build build

        - name: Create Archive
          run: |
            mkdir -p release/include
            mkdir -p release/lib
            cp -r includes/* release/include
            cp build/*.a release/lib
            tar -czvf CContainer.tar.gz -C release .
          shell: bash

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: CContainer.tar.gz
            path: CContainer.tar.gz

    release:
        needs: build
        runs-on: ubuntu-latest

        steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: CContainer.tar.gz

        - name: Create Release
          id: create_release
          uses: elgohr/Github-Release-Action@v5
          env:
            GITHUB_TOKEN: ${{ secrets.ACTION_RELEASE }}
          with:
            title: Release ${{ github.ref }}
            tag: ${{ github.ref }}
            # tag_name: ${{ github.ref }}
            # release_name: Release ${{ github.ref }}
            # body: |
            #   Changes in this Release
            #   - Added CContainer Library
            # draft: false
            # prerelease: false

        - name: Upload Release Asset
          id: upload-release-asset
          uses: softprops/action-gh-release@v2
          env:
            GITHUB_TOKEN: ${{ secrets.ACTION_RELEASE }}
          with:
            files: CContainer.tar.gz
            # upload_url: ${{ steps.create_release.outputs.upload_url }}
            # asset_path: CContainer.tar.gz
            # asset_name: CContainer.tar.gz
            # asset_content_type: application/gzip